### ISSUE TITLE
review.py error

### ISSUE THREAD

**Issue by g1ldedm1n1on** [GhostManager/DomainCheck#1]
Awesome project! Thank you for putting this together. 

Sorry I am not at a place where I can submit a pull request, however still wanted to submit this. There is an extra space causing an error when building out the CSV file.
Error:
File "/opt/DomainCheck/lib/review.py", line 636, in output_csv
    report_writer = csv.writer(report, delimiter=', ', quotechar='"', quoting=csv.QUOTE_MINIMAL)
TypeError: "delimiter" must be a 1-character string

Removing the extra space in review.py results in the CSV being correctly built.

**Comment by chrismaddalena** [comment]
Nice catch! Thanks for letting me know. I made a silly mistake when I tried fixing that line by adding a space between the delimiter and the comma. It's fixed in the latest push:

https://github.com/GhostManager/DomainCheck/blob/master/lib/review.py#L636
