### ISSUE TITLE
Talos: Incorrect Categorization

### ISSUE THREAD

**Issue by kcoble** [GhostManager/DomainCheck#4]
Checkup mode only produces a Talos category of "Uncategorized", which does not match manual queries of Web Category.

**Comment by chrismaddalena** [comment]
If Talos has a category for the domain the returned JSON should include a `category` key. DomainCheck looks for the key. If the key does not exist the assumed category is "Uncategorized" for Talos.

What does Talos' JSON show?

You can edit the `check_talos()` function to print the JSON to see what is returned for the specific domain.

https://github.com/GhostManager/DomainCheck/blob/master/lib/review.py#L232

**Comment by kcoble** [comment]
For whatever magical reason, it worked that time whereas I was getting None for category last week.

**Comment by chrismaddalena** [comment]
Hm, that always seems to happen when trying to debug something. Thanks for the update!

I'm actually going through DomainCheck to make some updates and intend to see if I can reproduce or find any other issues. Should be done before the 30th.
